name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    strategy: # we are using strategy if we need to run on parallel with different devices and version
      matrix:
        api-level: [30] # Google api level 
        target: [default]
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Espresso Tests
      uses: ReactiveCircus/android-emulator-runner@v2.22.0 # install and create the emulator
      with:
          api-level: 30
          target: default
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedDebugAndroidTest -Pcucumber -Ptags="@smoke"
